const articles={
architecture:{title:"SAP BASIS Architecture Explained",cat:"BASIS",html:`<div class="eyebrow">BASIS FUNDAMENTALS</div><h2>SAP BASIS Architecture Explained</h2><p>SAP BASIS is the technical administration layer that supports the SAP application, database, operating system and user connectivity.</p><h3>Core building blocks</h3><ul><li><b>ASCS:</b> Central services, primarily Message Server and Enqueue.</li><li><b>PAS:</b> Primary application server with dispatcher and work processes.</li><li><b>AAS:</b> Additional application servers used for scale and workload distribution.</li><li><b>Database:</b> Stores SAP application and business data; S/4HANA commonly uses SAP HANA.</li></ul><h3>What BASIS manages</h3><p>Availability, users and roles, jobs, spool, RFCs, transports, monitoring, performance, patches, upgrades, certificates, backups and technical troubleshooting.</p>`},
stms:{title:"STMS: Transport Management Made Simple",cat:"BASIS",html:`<div class="eyebrow">TRANSPORT MANAGEMENT</div><h2>STMS: Transport Management Made Simple</h2><p>STMS manages the controlled movement of SAP changes across the landscape.</p><h3>Key concepts</h3><ul><li>Transport Domain Controller and transport domain.</li><li>DEV → QAS → PRD transport routes.</li><li>Transport requests, import queues and return codes.</li><li>Import logs, cofiles/data files and dependency checks.</li></ul><h3>Common checks</h3><p>Validate the request, sequence, target system, import logs and return code before repeating a failed import.</p>`},
hana:{title:"SAP HANA System DB vs Tenant DB",cat:"HANA",html:`<div class="eyebrow">SAP HANA</div><h2>HANA System DB vs Tenant DB</h2><p>In a multitenant HANA system, the System Database provides system-level administration while tenant databases host application workloads and data.</p><h3>Simple model</h3><p>Think of the System DB as the control room and tenant DBs as individual databases. DEV, QAS and PRD are normally separate SAP systems; they are not automatically three tenants inside one HANA system.</p><h3>BASIS focus</h3><p>Monitor services, backups, memory, disk usage, alerts, users, connectivity and high-availability status.</p>`},
performance:{title:"Performance Analysis with ST03N & STAD",cat:"Troubleshooting",html:`<div class="eyebrow">PERFORMANCE</div><h2>Performance Analysis with ST03N & STAD</h2><p>Start with evidence. Identify the transaction, user, time window and affected system before deciding where the bottleneck is.</p><h3>ST03N</h3><p>Use workload analysis to identify trends and response-time components across transactions and users.</p><h3>STAD</h3><p>Drill into individual statistical records and compare response time, DB time, CPU time and wait components.</p><h3>Correlate</h3><p>Use SM50/SM66 for work processes, ST22 for dumps, SM21 for system events and database monitoring for DB-side evidence.</p>`},
migration:{title:"SUM & DMO: The S/4HANA Migration Picture",cat:"S/4HANA",html:`<div class="eyebrow">S/4HANA</div><h2>SUM & DMO: The Migration Picture</h2><p>SUM handles SAP software maintenance and upgrade processes. DMO adds database migration to SAP HANA as part of the SUM process in supported scenarios.</p><h3>Typical lifecycle</h3><ol><li>Assess target release and compatibility.</li><li>Use Maintenance Planner and validate add-ons.</li><li>Perform sizing, custom-code and readiness checks.</li><li>Prepare backups, downtime plan and technical prerequisites.</li><li>Execute SUM/DMO and validate the target system.</li></ol>`},
cloud:{title:"SAP Cloud Connector Explained",cat:"Cloud",html:`<div class="eyebrow">CLOUD</div><h2>SAP Cloud Connector Explained</h2><p>Cloud Connector provides a controlled bridge between selected on-premise resources and SAP cloud services.</p><h3>How it works</h3><p>The connector runs inside the corporate network, establishes a trusted connection to the cloud side and exposes only the required internal resources. This reduces the need to expose internal systems directly to the internet.</p>`},
installation:{title:"SAP Application Installation: BASIS Checklist",cat:"BASIS",html:`<div class="eyebrow">INSTALLATION</div><h2>SAP Application Installation: BASIS Checklist</h2><p>A BASIS installation normally includes infrastructure preparation, OS and filesystem checks, SAP media, database readiness, SAP software provisioning and post-installation validation.</p><h3>Important areas</h3><ul><li>Hostname, DNS, time synchronization and OS prerequisites.</li><li>Required SAP filesystems such as /usr/sap, /sapmnt and database-specific mounts.</li><li>SAP Host Agent and required OS packages.</li><li>SWPM / installation tool, SAP kernel and database connectivity.</li><li>Profiles, services, start/stop validation and post-installation checks.</li></ul>`},
security:{title:"SAP Security & User Administration",cat:"BASIS",html:`<div class="eyebrow">SECURITY</div><h2>SAP Security & User Administration</h2><p>BASIS commonly works with technical user administration and platform security controls.</p><h3>Key T-codes</h3><p>SU01 for users, PFCG for roles, SUIM for reporting and audit analysis, STRUST for certificates and trust configuration.</p><h3>Good practice</h3><p>Apply least privilege, control technical users, review expired accounts, document emergency access and protect certificate/private-key material.</p>`},
jobs:{title:"SAP Background Jobs",cat:"BASIS",html:`<div class="eyebrow">DAILY OPERATIONS</div><h2>SAP Background Jobs</h2><p>Background jobs execute scheduled SAP tasks without requiring an interactive user session.</p><h3>Useful transactions</h3><p>SM36 is used to schedule jobs and SM37 is used to monitor job status, logs, steps, duration and failures.</p><h3>Troubleshooting</h3><p>Check the job log, step details, variant, program, user authorization, dependent jobs, work processes and application logs before rerunning.</p>`},
spool:{title:"SAP Spool Administration",cat:"BASIS",html:`<div class="eyebrow">SPOOL</div><h2>SAP Spool Administration</h2><p>Spool management controls SAP output requests and their delivery to printers or other output destinations.</p><h3>Key transactions</h3><p>SP01 is used to monitor spool requests and SPAD is used for output devices and printer administration.</p>`},
rfc:{title:"SAP RFC & SM59",cat:"BASIS",html:`<div class="eyebrow">CONNECTIVITY</div><h2>SAP RFC & SM59</h2><p>Remote Function Calls allow SAP systems and external components to communicate through configured destinations.</p><h3>SM59 checks</h3><ul><li>Destination type and target host.</li><li>Connection test and authorization test.</li><li>Gateway/network reachability.</li><li>Technical user and password/certificate validity.</li></ul>`},
kernel:{title:"SAP Kernel Upgrade",cat:"BASIS",html:`<div class="eyebrow">LIFECYCLE</div><h2>SAP Kernel Upgrade</h2><p>The kernel contains core SAP executable components. Upgrades are performed to meet compatibility, security and support requirements.</p><h3>High-level flow</h3><p>Check PAM/support requirements → download compatible kernel → plan downtime → back up/verify → stop SAP → replace kernel files using the approved procedure → start SAP → validate processes, versions and application connectivity.</p>`},
sum:{title:"SUM, SPAM & SAINT",cat:"S/4HANA",html:`<div class="eyebrow">SAP LIFECYCLE</div><h2>SUM, SPAM & SAINT</h2><p>These tools serve different lifecycle purposes. SUM handles larger upgrade/update procedures; SPAM manages support packages; SAINT is used for add-on installation and upgrade activities.</p><h3>Interview point</h3><p>Always identify the target software component, SAP release, maintenance requirement and supported tool before choosing the procedure.</p>`},
refresh:{title:"System Refresh vs Client Copy",cat:"BASIS",html:`<div class="eyebrow">SYSTEM ADMINISTRATION</div><h2>System Refresh vs Client Copy</h2><p>A system refresh replaces or synchronizes a target system's data/configuration from a source system according to the chosen refresh procedure. A client copy moves client-specific data inside or between SAP systems using supported client-copy methods.</p><h3>Simple distinction</h3><p>System refresh is a broader system-level activity; client copy is focused on a client and its data.</p>`},
ha:{title:"SAP High Availability & HANA Replication",cat:"Troubleshooting",html:`<div class="eyebrow">HIGH AVAILABILITY</div><h2>High Availability & HANA System Replication</h2><p>HA design aims to reduce service interruption when infrastructure or software components fail.</p><h3>Common concepts</h3><p>ASCS/ERS for central services protection, clustering/failover at the infrastructure layer, and HANA System Replication for database availability. Always validate the actual HA design and runbook before a failover.</p>`},
solman:{title:"SAP Solution Manager & Managed Systems",cat:"BASIS",html:`<div class="eyebrow">SAP OPERATIONS</div><h2>Solution Manager & Managed Systems</h2><p>SAP Solution Manager can provide monitoring, service management, diagnostics and lifecycle capabilities for managed SAP systems.</p><h3>Typical BASIS work</h3><p>Establish trusted connections, configure managed-system data, agents and monitoring, then validate technical system information and alerts.</p>`},
backup:{title:"SAP HANA Backup & Recovery",cat:"HANA",html:`<div class="eyebrow">DATABASE</div><h2>SAP HANA Backup & Recovery</h2><p>A backup strategy should protect data against logical errors, infrastructure failures and disaster scenarios.</p><h3>BASIS checklist</h3><p>Define full/data backups, log backups, retention, destination capacity, encryption where required, monitoring and periodic restore testing. A backup is only useful if recovery is tested.</p>`},
ssl:{title:"SAP SSL Certificates & STRUST",cat:"Cloud",html:`<div class="eyebrow">CERTIFICATES</div><h2>SAP SSL Certificates & STRUST</h2><p>STRUST is used to manage SAP PSEs and trust certificates for secure communication.</p><h3>Renewal mindset</h3><p>Check certificate expiry, obtain the correct signed certificate chain, update the appropriate PSE, validate the trust chain and test the affected HTTPS/RFC/integration connection.</p>`},
aws:{title:"SAP on AWS: BASIS Perspective",cat:"Cloud",html:`<div class="eyebrow">CLOUD OPERATIONS</div><h2>SAP on AWS: BASIS Perspective</h2><p>Running SAP on AWS combines SAP administration with cloud infrastructure concepts such as EC2, storage, networking, security groups, load balancing, DNS, backup and monitoring.</p><h3>BASIS focus</h3><p>Understand where the SAP layer ends and the cloud infrastructure layer begins, then work with the AWS team using clear evidence and ownership boundaries.</p>`},
};

const scenarioGuides={
systemdown:{title:"SAP System Down — Incident Playbook",cat:"P1 / Availability",html:`<h2>SAP System Down — Incident Playbook</h2><p><b>Goal:</b> restore service safely while preserving evidence for RCA.</p><h3>1. Confirm the symptom</h3><p>Check whether the issue affects all users, one application server, one interface, or the entire system. Confirm the exact start time.</p><h3>2. Check the infrastructure layer</h3><ul><li>Server/VM reachable?</li><li>CPU, memory and filesystem healthy?</li><li>Required mounts available?</li><li>Database host reachable?</li></ul><h3>3. Check SAP processes</h3><p>Use <code>sapcontrol -nr &lt;NN&gt; -function GetProcessList</code>. Identify whether ASCS, PAS, AAS or other services are stopped/grey.</p><h3>4. Read evidence</h3><p>Review SAP work-process traces, message server traces, system logs and database alerts around the incident timestamp.</p><h3>5. Recovery</h3><p>Follow the approved restart/failover runbook. Validate logon, transactions, RFCs, jobs and interfaces after recovery.</p><h3>RCA evidence</h3><p>Capture timeline, failed component, error text, actions taken, recovery time and preventive action.</p>`},
slow:{title:"SAP Slow — Performance Playbook",cat:"P1 / Performance",html:`<h2>SAP Slow — Performance Playbook</h2><h3>Start with four questions</h3><ol><li>Who is affected?</li><li>Which transaction/process?</li><li>When did it start?</li><li>Is it consistently slow or intermittent?</li></ol><h3>Evidence path</h3><p><b>ST03N</b> → identify workload and response-time pattern → <b>STAD</b> → drill into individual records → <b>SM50/SM66</b> → inspect work processes → DB/infrastructure monitoring → correlate changes.</p><h3>Do not guess</h3><p>A high response time does not automatically mean the database is the problem. Compare DB time, CPU time and wait components and use evidence to isolate the layer.</p>`},
transport:{title:"Transport RC 8 / RC 12 — Troubleshooting",cat:"HIGH / Transport",html:`<h2>Transport RC 8 / RC 12 — Troubleshooting</h2><h3>First action</h3><p>Open the import log in STMS and find the first meaningful error. Later errors may be consequences.</p><h3>Check</h3><ul><li>Object and program/class/table mentioned in the log.</li><li>Transport sequence and dependencies.</li><li>Target system availability and filesystem space.</li><li>DDIC/object activation or syntax issues.</li><li>Whether a previous transport changed the same object.</li></ul><h3>Recovery</h3><p>Coordinate with the development/application owner, correct the root cause, create the appropriate follow-up transport if needed, then re-import through the normal change process.</p>`},
hanaDisk:{title:"HANA Disk Usage Critical — Troubleshooting",cat:"HIGH / Database",html:`<h2>HANA Disk Usage Critical — Troubleshooting</h2><h3>Separate the problem</h3><p>Determine whether the growth is in data/persistence, log area, backup destination or an operating-system filesystem.</p><h3>Check</h3><ul><li>Filesystem capacity and growth rate.</li><li>HANA alerts and database usage.</li><li>Recent backup/log-backup behavior.</li><li>Long-running transactions or unusual workload.</li></ul><h3>Important</h3><p>Never manually delete database files to create space. Use the approved HANA/storage procedure and coordinate with the DB/storage team for capacity or cleanup actions.</p>`},
job:{title:"Cancelled Background Job — Troubleshooting",cat:"MEDIUM / Jobs",html:`<h2>Cancelled Background Job — Troubleshooting</h2><h3>SM37 checklist</h3><ol><li>Open job log.</li><li>Identify the failed step and program.</li><li>Check the executing user.</li><li>Check ST22 for an ABAP dump.</li><li>Check application logs and variants.</li><li>Check system/work-process resources if the job terminated due to resource constraints.</li></ol><p>Only rerun after confirming whether the failure was transient or caused by data, configuration or authorization.</p>`},
rfc:{title:"RFC Failure — Troubleshooting",cat:"MEDIUM / Connectivity",html:`<h2>RFC Failure — Troubleshooting</h2><h3>SM59 sequence</h3><ol><li>Run Connection Test.</li><li>Run Authorization Test where applicable.</li><li>Check destination host/service and network reachability.</li><li>Check technical user, password or certificate.</li><li>Check gateway and relevant traces if required.</li></ol><p>Classify the failure as network, authentication/authorization, SAP destination configuration or target application failure.</p>`},
ssl:{title:"Expired SSL Certificate — Troubleshooting",cat:"MEDIUM / Security",html:`<h2>Expired SSL Certificate — Troubleshooting</h2><ol><li>Confirm the expiry date and affected endpoint.</li><li>Identify the correct PSE in STRUST.</li><li>Obtain the approved certificate and full trust chain.</li><li>Update the PSE following the change procedure.</li><li>Validate the certificate chain and retest the integration.</li></ol><p>Record the new expiry date and establish monitoring/reminders so the issue does not recur.</p>`},
user:{title:"SAP User Login Failure — Troubleshooting",cat:"MEDIUM / Users",html:`<h2>SAP User Login Failure — Troubleshooting</h2><h3>Separate the symptom</h3><p>Is the user locked, password expired, unauthorized for the transaction, unable to authenticate through SSO, or unable to reach the system?</p><h3>Checks</h3><p>Use SU01 for user status, review the exact error message, and for SSO/Fiori scenarios validate the trust/authentication path. Avoid assigning broad roles as a quick fix.</p>`}
};

const grid=document.getElementById("articleGrid"), search=document.getElementById("articleSearch"), filter=document.getElementById("categoryFilter"), noResults=document.getElementById("noResults");
function applyFilters(){const q=search.value.toLowerCase(), f=filter.value;let shown=0;document.querySelectorAll(".article-card").forEach(c=>{const ok=(f==="all"||c.dataset.category===f)&&(c.dataset.title.toLowerCase().includes(q)||c.innerText.toLowerCase().includes(q));c.style.display=ok?"flex":"none";if(ok)shown++});noResults.style.display=shown?"none":"block"}
search.addEventListener("input",applyFilters);filter.addEventListener("change",applyFilters);

const modal=document.getElementById("modal"), content=document.getElementById("modalContent");
document.querySelectorAll(".read-btn").forEach(b=>b.addEventListener("click",()=>{content.innerHTML=articles[b.dataset.article].html;modal.classList.add("open");document.body.style.overflow="hidden"}));
document.getElementById("closeModal").onclick=()=>{modal.classList.remove("open");document.body.style.overflow=""};
modal.addEventListener("click",e=>{if(e.target===modal){modal.classList.remove("open");document.body.style.overflow=""}});

const overlay=document.getElementById("searchOverlay"), gs=document.getElementById("globalSearch"), results=document.getElementById("searchResults");
document.getElementById("searchBtn").onclick=()=>{overlay.classList.add("open");gs.focus()};
document.getElementById("closeSearch").onclick=()=>overlay.classList.remove("open");
gs.addEventListener("input",()=>{const q=gs.value.toLowerCase().trim();results.innerHTML="";if(!q)return;Object.entries(articles).filter(([k,a])=>(a.title+" "+a.cat).toLowerCase().includes(q)).forEach(([k,a])=>{const d=document.createElement("div");d.className="result";d.innerHTML=`<b>${a.title}</b><small>${a.cat} · Read article</small>`;d.onclick=()=>{overlay.classList.remove("open");content.innerHTML=a.html;modal.classList.add("open");document.body.style.overflow="hidden"};results.appendChild(d)})});

document.getElementById("themeBtn").onclick=()=>document.body.classList.toggle("light");
document.getElementById("menuBtn").onclick=()=>{const n=document.getElementById("nav");n.style.display=n.style.display==="flex"?"none":"flex";n.style.position="absolute";n.style.top="72px";n.style.left="0";n.style.right="0";n.style.padding="20px";n.style.background="#07111f";n.style.flexDirection="column"};

document.querySelectorAll(".scenario-btn").forEach(b=>b.addEventListener("click",()=>{
  const s=scenarioGuides[b.dataset.scenario];
  content.innerHTML=`<div class="eyebrow">${s.cat}</div>${s.html}`;
  modal.classList.add("open");
  document.body.style.overflow="hidden";
}));

window.addEventListener("scroll",()=>{const h=document.documentElement.scrollHeight-innerHeight;document.getElementById("progress").style.width=(scrollY/h*100)+"%"});

/* ===== BASIS NEXUS v4 ULTIMATE ENHANCEMENTS ===== */
(function(){
  const extraCSS = `
  .ultimate-section{background:linear-gradient(135deg,rgba(53,216,255,.045),rgba(169,108,255,.055));border-top:1px solid var(--border);border-bottom:1px solid var(--border)}
  .ultimate-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.ultimate-card{background:var(--panel);border:1px solid var(--border);border-radius:18px;padding:22px;transition:.25s;cursor:pointer}.ultimate-card:hover{transform:translateY(-5px);border-color:rgba(53,216,255,.45);box-shadow:var(--shadow)}
  .diagram-large{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;align-items:center;margin:25px 0}.diagram-box{padding:17px 10px;text-align:center;border-radius:14px;background:linear-gradient(145deg,var(--panel2),var(--panel));border:1px solid var(--border);font-weight:800;font-size:12px}.diagram-arrow{text-align:center;color:var(--cyan);font-size:22px}
  .star-method{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:22px 0}.star-method>div{padding:17px;border-radius:15px;background:var(--panel);border:1px solid var(--border)}.star-method b{font-size:24px;color:var(--cyan)}.star-method span{display:block;font-weight:800}.star-method small{color:var(--muted)}
  .interview-list{display:grid;grid-template-columns:1fr 1fr;gap:15px}.interview-item{background:var(--panel);border:1px solid var(--border);border-radius:16px;overflow:hidden}.interview-q{padding:17px;cursor:pointer;display:flex;justify-content:space-between;gap:15px}.interview-q b{font-size:14px}.interview-a{display:none;border-top:1px solid var(--border);padding:0 18px 18px}.interview-item.open .interview-a{display:block}.star-block{margin-top:13px;padding:12px 14px;border-left:3px solid var(--cyan);background:rgba(53,216,255,.035);border-radius:0 10px 10px 0}.star-block strong{display:block;color:var(--cyan);font-size:10px;letter-spacing:.14em;text-transform:uppercase}.star-block p{margin:4px 0;color:var(--muted);font-size:13px}.tip-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.tip{padding:18px;border:1px solid var(--border);border-radius:15px;background:var(--panel)}.tip h4{margin:0 0 7px}.tip p{font-size:12px;color:var(--muted)}
  .modal-panel{max-width:1100px}.modal-panel p,.modal-panel li{font-size:15px;line-height:1.75}.modal-panel h3{font-size:20px}.modal-panel .deep-section{margin-top:28px;padding-top:20px;border-top:1px solid var(--border)}
  @media(max-width:950px){.ultimate-grid,.interview-list,.tip-grid{grid-template-columns:1fr 1fr}.star-method{grid-template-columns:1fr 1fr}.diagram-large{grid-template-columns:1fr 30px 1fr 30px 1fr}}
  @media(max-width:650px){.ultimate-grid,.interview-list,.tip-grid,.star-method{grid-template-columns:1fr}.diagram-large{grid-template-columns:1fr}.diagram-arrow{transform:rotate(90deg)}}`;
  const st=document.createElement('style');st.textContent=extraCSS;document.head.appendChild(st);

  const interview=[
  {q:'Tell me about a critical SAP system-down incident you handled.',s:'A production SAP system became unavailable and multiple users reported that they could not log in.',t:'I needed to quickly identify the failed layer, restore service safely and keep stakeholders updated.',a:'I first confirmed the impact and exact start time. I checked OS connectivity, SAP process status with sapcontrol, application traces, SM21 and database availability. I isolated the failed component instead of immediately restarting the whole stack. After the corrective action, I restarted only the required service through the approved procedure and validated logon, transactions, RFCs, jobs and monitoring.',r:'The system was restored in a controlled manner. I documented the timeline, root cause and preventive action so the same failure could be detected earlier.'},
  {q:'How do you troubleshoot SAP performance issues using ST03N and STAD?',s:'Users reported that a normally fast transaction had become slow during business hours.',t:'I had to determine whether the delay was caused by ABAP processing, database time, locks, work-process saturation or infrastructure.',a:'I captured the exact transaction, user and time window. I checked ST03N to identify the workload and response-time pattern, then STAD to drill into individual executions. I correlated the findings with SM50/SM66, SM12, HANA monitoring and OS metrics. I compared the current result with a normal baseline before deciding the root cause.',r:'This produced an evidence-based RCA instead of simply saying “SAP is slow”. The same metrics were used after the fix to validate improvement.'},
  {q:'Explain a transport RC 8/12 troubleshooting scenario.',s:'A transport imported into QAS ended with return code 8.',t:'I needed to identify the first meaningful error and determine whether it was transport execution or incorrect transport content.',a:'I opened STMS import history and reviewed the detailed log. I identified the failing object and phase, checked transport sequence and dependencies, and reviewed tp/R3trans information where relevant. If the content was incorrect, I coordinated with the developer/application owner instead of changing application objects myself. After correction, I followed the approved re-import process and validated the log.',r:'The corrected transport completed successfully and the root cause was communicated. The approach avoided repeated blind imports.'},
  {q:'Tell me about an SSL certificate expiry incident.',s:'An SAP integration stopped working because a certificate had expired.',t:'I needed to restore secure connectivity without creating a trust-chain or configuration problem.',a:'I identified the exact endpoint and PSE, confirmed the expiry and backed up the existing configuration. I obtained the renewed certificate and required CA chain, updated the appropriate PSE through the approved change process, and restarted only the affected service when necessary. I tested the endpoint from the consuming application, not only from the SAP server.',r:'Connectivity was restored and the full certificate chain was validated. I recommended monitoring and advance renewal to prevent recurrence.'},
  {q:'How do you handle a cancelled background job?',s:'A critical scheduled job changed to CANCELLED status.',t:'I needed to identify whether the cause was application logic, authorization, lock contention, data, or infrastructure.',a:'I checked SM37 for the job log, step, program, variant, user and spool. I correlated the cancellation timestamp with ST22 and SM21, then checked SM12 and SM50/SM66 when relevant. I involved the application owner when the evidence pointed to program/data logic. Before rerunning, I checked for duplicate-processing risk.',r:'The job completed successfully after the correct corrective action, and the cause was documented instead of treating the cancellation as a one-off.'},
  {q:'How would you troubleshoot a user who cannot log in?',s:'One user reported a login failure while other users were working normally.',t:'I needed to prove whether it was a user/account issue rather than a system outage.',a:'I checked SU01 for lock status, validity and password state, confirmed the client and exact error, and checked whether the user could reach the system. I avoided assigning broad roles as a quick fix. If the issue was SSO-related, I checked the authentication/trust path and relevant logs.',r:'The issue was isolated to the correct layer and resolved without unnecessary changes to the SAP system.'},
  {q:'How do you approach HANA disk-space critical alerts?',s:'HANA storage utilisation crossed the critical threshold and continued to grow.',t:'I needed to prevent a database outage while identifying the source of growth.',a:'I checked filesystem usage and growth rate, HANA alerts, data/log areas and backup destinations. I reviewed recent changes and workload. I did not delete database-managed files manually. I coordinated approved cleanup or capacity extension with the DB/storage team and monitored the result.',r:'Capacity was restored before an outage occurred and the growth trend was added to preventive monitoring.'},
  {q:'Describe your approach to an S/4HANA migration from the BASIS side.',s:'The organisation planned an ECC-to-S/4HANA transformation using a supported SUM/DMO approach.',t:'I would be responsible for technical preparation, execution support, monitoring, downtime coordination and post-migration validation.',a:'I would begin with release/PAM assessment, Maintenance Planner, add-on and custom-code readiness, sizing, filesystem capacity, backups and interface dependencies. I would prepare SUM, validate prerequisites, monitor phases and logs, coordinate downtime, and perform post-migration checks for HANA, instances, jobs, RFCs, printers, interfaces and business transactions.',r:'The target system would be accepted only after technical and business validation. I would document issues, timings and lessons learned for future cutovers.'},
  {q:'How do you write an RCA for a recurring SAP issue?',s:'The same production incident was occurring repeatedly even though service was restored each time.',t:'I needed to move the team from symptom recovery to permanent corrective action.',a:'I collected incident timestamps, logs, monitoring data and change history. I built a timeline, identified the immediate cause and contributing factors, and used 5-Why analysis. I separated corrective action from preventive action and assigned owners and due dates.',r:'The RCA became actionable, recurrence could be measured, and monitoring or process changes were introduced to detect the condition earlier.'},
  {q:'How do you handle a high-severity production incident?',s:'A business-critical SAP process became unavailable during working hours.',t:'I needed to restore business service while maintaining technical control and clear communication.',a:'I established scope and impact, opened a bridge where required, assigned owners, collected timestamps and evidence, and worked layer by layer. I communicated short factual updates, avoided risky unapproved changes, and validated the full service chain after recovery.',r:'Business service was restored with controlled communication and a documented RCA. The preventive actions were tracked separately from the immediate fix.'},
  {q:'How do you validate SAP after a restart or maintenance activity?',s:'A planned maintenance window was completed and the SAP system had been started again.',t:'I needed to prove the system was ready for business use, not just that processes were green.',a:'I checked SAP and HANA process status, SM21, ST22, work processes, background jobs, RFCs, interfaces, spool, users and key transactions. I also reviewed monitoring for fresh errors and confirmed dependent systems were reachable.',r:'The system was declared ready only after technical and business validation passed. This reduced the chance of closing a maintenance window with hidden issues.'},
  {q:'How would you answer an interviewer asking about implementation experience if you did not own a full implementation?',s:'The job description asks for SAP BASIS implementation experience, but my strongest experience is in administration, operations and troubleshooting.',t:'I need to be honest while showing that I understand the implementation lifecycle and can contribute.',a:'I would say: “I would not claim ownership of a full greenfield implementation if I did not personally do it. My strength is technical operations, administration, monitoring, incident handling and lifecycle activities. I understand the BASIS implementation workstream — architecture, installation, connectivity, transports, technical configuration, testing, cutover and hypercare — and I can explain the activities and my actual hands-on exposure clearly.”',r:'This gives the interviewer an accurate picture while demonstrating maturity, technical understanding and willingness to learn.'},
  {q:'How do you troubleshoot an RFC connection failure?',s:'An interface team reported that an RFC destination had stopped connecting.',t:'I needed to identify whether the cause was destination configuration, credentials, network, gateway or target-system availability.',a:'I tested the destination in SM59, checked connection and authorization results, verified host/system/client and technical-user validity, then checked network reachability and target-system status. Where required, I correlated with gateway/application traces.',r:'The RFC was restored and the dependent interface was tested end to end. The final RCA identified the exact failure layer rather than simply stating “RFC failed”.'},
  {q:'What makes a good SAP BASIS engineer?',s:'Production systems require reliable administration and calm handling of unexpected failures.',t:'The goal is stable service, not merely completing technical tasks.',a:'I focus on architecture understanding, evidence-based troubleshooting, clear communication and validation. I also document recurring problems and convert them into monitoring, automation or preventive actions.',r:'This improves operational stability and makes future incidents faster to diagnose because the team learns from previous failures.'}
  ];

  const interviewSection=document.createElement('section');
  interviewSection.className='section ultimate-section';interviewSection.id='interview';
  interviewSection.innerHTML=`<div class="section-head"><div><div class="eyebrow">INTERVIEW LAB</div><h2>STAR-based SAP BASIS Interview Answers</h2><p class="section-intro">These are model answers. Adapt the facts, tools and results to your actual experience — never claim work you did not perform.</p></div><button id="randomStar" class="scenario-btn">🎯 Random STAR Question</button></div>
  <div class="star-method"><div><b>S</b><span>Situation</span><small>Set the context in 1–2 sentences.</small></div><div><b>T</b><span>Task</span><small>Explain your responsibility.</small></div><div><b>A</b><span>Action</span><small>Spend most of the answer here.</small></div><div><b>R</b><span>Result</span><small>Give outcome + prevention.</small></div></div>
  <div id="starList" class="interview-list"></div>`;
  const about=document.getElementById('about'); if(about) about.parentNode.insertBefore(interviewSection,about);
  const starList=document.getElementById('starList');
  function renderInterview(list){starList.innerHTML=list.map((x,i)=>`<div class="interview-item"><div class="interview-q"><b>${i+1}. ${x.q}</b><span>＋</span></div><div class="interview-a"><div class="star-block"><strong>Situation</strong><p>${x.s}</p></div><div class="star-block"><strong>Task</strong><p>${x.t}</p></div><div class="star-block"><strong>Action</strong><p>${x.a}</p></div><div class="star-block"><strong>Result</strong><p>${x.r}</p></div></div></div>`).join('');
    starList.querySelectorAll('.interview-q').forEach(h=>h.onclick=()=>{const item=h.parentElement;item.classList.toggle('open');h.querySelector('span').textContent=item.classList.contains('open')?'−':'＋'});
  }
  renderInterview(interview);
  document.getElementById('randomStar').onclick=()=>{renderInterview([interview[Math.floor(Math.random()*interview.length)]]);starList.querySelector('.interview-item').classList.add('open');document.getElementById('interview').scrollIntoView({behavior:'smooth'})};

  const visual=document.createElement('section');visual.className='section';visual.id='visuals';
  visual.innerHTML=`<div class="section-head"><div><div class="eyebrow">VISUAL LEARNING</div><h2>Colourful BASIS architecture maps</h2><p class="section-intro">Use these diagrams to explain concepts in interviews without memorising paragraphs.</p></div></div>
  <div class="ultimate-grid">
   <div class="ultimate-card" data-v="sap"><h3>🏗️ SAP 3-Tier Architecture</h3><p>Explain user → application → database and where BASIS operates.</p><div class="diagram-large"><div class="diagram-box">USER / GUI</div><div class="diagram-arrow">→</div><div class="diagram-box">ASCS + APP SERVERS</div><div class="diagram-arrow">→</div><div class="diagram-box">HANA DB</div></div></div>
   <div class="ultimate-card" data-v="hana"><h3>🧠 HANA MDC</h3><p>Simple SystemDB and tenant explanation.</p><div class="diagram-large"><div class="diagram-box">HANA SYSTEM</div><div class="diagram-arrow">→</div><div class="diagram-box">SYSTEMDB</div><div class="diagram-arrow">+</div><div class="diagram-box">TENANTS</div></div></div>
   <div class="ultimate-card" data-v="transport"><h3>📦 Transport Flow</h3><p>Show controlled DEV → QAS → PRD movement.</p><div class="diagram-large"><div class="diagram-box">DEV</div><div class="diagram-arrow">→</div><div class="diagram-box">QAS</div><div class="diagram-arrow">→</div><div class="diagram-box">PRD</div></div></div>
   <div class="ultimate-card" data-v="incident"><h3>🚨 Incident Lifecycle</h3><p>Use this flow for almost every production scenario.</p><div class="diagram-large"><div class="diagram-box">DETECT</div><div class="diagram-arrow">→</div><div class="diagram-box">ISOLATE</div><div class="diagram-arrow">→</div><div class="diagram-box">FIX</div></div></div>
   <div class="ultimate-card" data-v="migration"><h3>🚚 S/4HANA Migration</h3><p>Assessment through SUM/DMO and post-cutover validation.</p><div class="diagram-large"><div class="diagram-box">ASSESS</div><div class="diagram-arrow">→</div><div class="diagram-box">SUM/DMO</div><div class="diagram-arrow">→</div><div class="diagram-box">VALIDATE</div></div></div>
   <div class="ultimate-card" data-v="cloud"><h3>☁️ Cloud Connector</h3><p>Secure, controlled connectivity between on-premise and SAP cloud.</p><div class="diagram-large"><div class="diagram-box">ON-PREM</div><div class="diagram-arrow">⇄</div><div class="diagram-box">CLOUD CONNECTOR</div><div class="diagram-arrow">⇄</div><div class="diagram-box">BTP</div></div></div>
  </div>`;
  const topics=document.getElementById('topics'); if(topics) topics.parentNode.insertBefore(visual,topics);
  const visualData={
   sap:`<h2>How to explain SAP architecture in an interview</h2><p>Start with the request path: a user sends a request from SAP GUI or browser. The request reaches an SAP application server/dispatcher, is assigned to an appropriate work process, and the application accesses the database. Central services such as message server and enqueue support communication and locking.</p><div class="callout"><b>Interview sentence:</b> “I troubleshoot from the outside in: user/network, application server and work process, database, then OS and storage.”</div>`,
   hana:`<h2>How to explain HANA MDC</h2><p>The HANA system contains system-level services and databases. The SystemDB is used for system administration, while tenant databases are isolated database containers used for application workloads. Do not confuse this with DEV/QAS/PRD, which are usually separate SAP systems.</p>`,
   transport:`<h2>How to explain STMS</h2><p>Development changes are captured in transport requests. After release, the request is moved through the configured transport landscape. BASIS controls the technical import and log analysis, while the application team validates the business functionality.</p>`,
   incident:`<h2>Universal production troubleshooting model</h2><p><b>Detect → Scope → Collect evidence → Isolate → Fix → Validate → RCA.</b> This model is more valuable in an interview than memorising dozens of isolated commands.</p>`,
   migration:`<h2>S/4HANA migration explanation</h2><p>Describe the lifecycle rather than only naming DMO: assess compatibility, plan with Maintenance Planner, validate add-ons/custom code, prepare infrastructure and backups, execute SUM/DMO, monitor phases/logs, coordinate downtime, then validate interfaces, jobs, RFCs, printers and business transactions.</p>`,
   cloud:`<h2>Cloud Connector explanation</h2><p>Cloud Connector provides controlled connectivity between on-premise resources and SAP cloud services. BASIS manages connectivity configuration, mappings, certificates and monitoring while keeping the exposed resource scope minimal.</p>`
  };
  visual.querySelectorAll('.ultimate-card').forEach(c=>c.onclick=()=>{content.innerHTML=visualData[c.dataset.v];modal.classList.add('open');document.body.style.overflow='hidden'});

  // Make every existing scenario button reliable through event delegation.
  document.addEventListener('click',function(e){const b=e.target.closest('.scenario-btn');if(!b||b.id==='randomStar')return;const key=b.dataset.scenario; if(window.scenarioGuides && window.scenarioGuides[key]){const s=window.scenarioGuides[key];content.innerHTML=`<div class="eyebrow">${s.cat}</div>${s.html}`;modal.classList.add('open');document.body.style.overflow='hidden'}});

  // Make article modal content more detailed for the most commonly asked topics.
  const deep={
   performance:`<div class="deep-section"><h3>Deep troubleshooting sequence</h3><ol><li>Capture exact timestamp, transaction, user and system/client.</li><li>ST03N: identify response-time trend and workload category.</li><li>STAD: drill into the statistical record.</li><li>SM50/SM66: correlate long-running work processes.</li><li>SM12: check blocking locks where applicable.</li><li>HANA/DB: check DB time, expensive SQL and resource pressure.</li><li>OS: CPU, memory, swap, disk I/O and filesystem capacity.</li><li>Validate with the same measurement after remediation.</li></ol><div class="warnbox"><b>Never conclude from one metric.</b> Correlation across SAP, database and OS evidence is what turns a symptom into an RCA.</div></div>`,
   stms:`<div class="deep-section"><h3>Transport failure decision tree</h3><p><b>RC 8/12?</b> → read the first meaningful error → identify object/phase → check dependency/sequence → check target technical health → decide whether BASIS or application owner owns the correction → re-import through change control → validate.</p></div>`,
   hana:`<div class="deep-section"><h3>HANA interview checkpoints</h3><ul><li>Explain SystemDB vs tenant DB.</li><li>Explain HANA memory and disk at a high level.</li><li>Know backup and log-backup concepts.</li><li>Know how to check process health.</li><li>Know how HANA System Replication contributes to HA.</li></ul></div>`,
   migration:`<div class="deep-section"><h3>BASIS migration checklist</h3><ul><li>Compatibility/PAM and target release.</li><li>Maintenance Planner / stack information.</li><li>Add-on and custom-code readiness.</li><li>Sizing, filesystem and backup checks.</li><li>SUM/DMO media, kernel and permissions.</li><li>Pre-checks and sandbox rehearsal.</li><li>Downtime communication and cutover.</li><li>Post-migration interfaces, jobs, RFCs, spool and business validation.</li></ul></div>`
  };
  Object.keys(deep).forEach(k=>{if(articles[k])articles[k].html+=deep[k]});
})();
