const articles={
architecture:{title:"SAP BASIS Architecture Explained",cat:"BASIS",html:`<div class="eyebrow">BASIS FUNDAMENTALS</div><h2>SAP BASIS Architecture Explained</h2><p>SAP BASIS is the technical administration layer that supports the SAP application, database, operating system and user connectivity.</p><h3>Core building blocks</h3><ul><li><b>ASCS:</b> Central services, primarily Message Server and Enqueue.</li><li><b>PAS:</b> Primary application server with dispatcher and work processes.</li><li><b>AAS:</b> Additional application servers used for scale and workload distribution.</li><li><b>Database:</b> Stores SAP application and business data; S/4HANA commonly uses SAP HANA.</li></ul><h3>What BASIS manages</h3><p>Availability, users and roles, jobs, spool, RFCs, transports, monitoring, performance, patches, upgrades, certificates, backups and technical troubleshooting.</p>`},
stms:{title:"STMS: Transport Management Made Simple",cat:"BASIS",html:`<div class="eyebrow">TRANSPORT MANAGEMENT</div><h2>STMS: Transport Management Made Simple</h2><p>STMS manages the controlled movement of SAP changes across the landscape.</p><h3>Key concepts</h3><ul><li>Transport Domain Controller and transport domain.</li><li>DEV → QAS → PRD transport routes.</li><li>Transport requests, import queues and return codes.</li><li>Import logs, cofiles/data files and dependency checks.</li></ul><h3>Common checks</h3><p>Validate the request, sequence, target system, import logs and return code before repeating a failed import.</p>`},
hana:{title:"SAP HANA System DB vs Tenant DB",cat:"HANA",html:`<div class="eyebrow">SAP HANA</div><h2>HANA System DB vs Tenant DB</h2><p>In a multitenant HANA system, the System Database provides system-level administration while tenant databases host application workloads and data.</p><h3>Simple model</h3><p>Think of the System DB as the control room and tenant DBs as individual databases. DEV, QAS and PRD are normally separate SAP systems; they are not automatically three tenants inside one HANA system.</p><h3>BASIS focus</h3><p>Monitor services, backups, memory, disk usage, alerts, users, connectivity and high-availability status.</p>`},
performance:{title:"Performance Analysis with ST03N & STAD",cat:"Troubleshooting",html:`<div class="eyebrow">PERFORMANCE</div><h2>Performance Analysis with ST03N & STAD</h2><p>Start with evidence. Identify the transaction, user, time window and affected system before deciding where the bottleneck is.</p><h3>ST03N</h3><p>Use workload analysis to identify trends and response-time components across transactions and users.</p><h3>STAD</h3><p>Drill into individual statistical records and compare response time, DB time, CPU time and wait components.</p><h3>Correlate</h3><p>Use SM50/SM66 for work processes, ST22 for dumps, SM21 for system events and database monitoring for DB-side evidence.</p>`},
migration:{title:"SUM & DMO: The S/4HANA Migration Picture",cat:"S/4HANA",html:`<div class="eyebrow">S/4HANA</div><h2>SUM & DMO: The Migration Picture</h2><p>SUM handles SAP software maintenance and upgrade processes. DMO adds database migration to SAP HANA as part of the SUM process in supported scenarios.</p><h3>Typical lifecycle</h3><ol><li>Assess target release and compatibility.</li><li>Use Maintenance Planner and validate add-ons.</li><li>Perform sizing, custom-code and readiness checks.</li><li>Prepare backups, downtime plan and technical prerequisites.</li><li>Execute SUM/DMO and validate the target system.</li></ol>`},
cloud:{title:"SAP Cloud Connector Explained",cat:"Cloud",html:`<div class="eyebrow">CLOUD</div><h2>SAP Cloud Connector Explained</h2><p>Cloud Connector provides a controlled bridge between selected on-premise resources and SAP cloud services.</p><h3>How it works</h3><p>The connector runs inside the corporate network, establishes a trusted connection to the cloud side and exposes only the required internal resources. This reduces the need to expose internal systems directly to the internet.</p>`},
installation:{title:"SAP Application Installation: BASIS Checklist",cat:"BASIS",html:`<div class="eyebrow">INSTALLATION</div><h2>SAP Application Installation: BASIS Checklist</h2><p>A BASIS installation normally includes infrastructure preparation, OS and filesystem checks, SAP media, database readiness, SAP software provisioning and post-installation validation.</p><h3>Important areas</h3><ul><li>Hostname, DNS, time synchronization and OS prerequisites.</li><li>Required SAP filesystems such as /usr/sap, /sapmnt and database-specific mounts.</li><li>SAP Host Agent and required OS packages.</li><li>SWPM / installation tool, SAP kernel and database connectivity.</li><li>Profiles, services, start/stop validation and post-installation checks.</li></ul>`},
security:{title:"SAP Security & User Administration",cat:"BASIS",html:`<div class="eyebrow">SECURITY</div><h2>SAP Security & User Administration</h2><p>BASIS commonly works with technical user administration and platform security controls.</p><h3>Key T-codes</h3><p>SU01 for users, PFCG for roles, SUIM for reporting and audit analysis, STRUST for certificates and trust configuration.</p><h3>Good practice</h3><p>Apply least privilege, control technical users, review expired accounts, document emergency access and protect certificate/private-key material.</p>`},
jobs:{title:"SAP Background Jobs",cat:"BASIS",html:`<div class="eyebrow">DAILY OPERATIONS</div><h2>SAP Background Jobs</h2><p>Background jobs execute scheduled SAP tasks without requiring an interactive user session.</p><h3>Useful transactions</h3><p>SM36 is used to schedule jobs and SM37 is used to monitor job status, logs, steps, duration and failures.</p><h3>Troubleshooting</h3><p>Check the job log, step details, variant, program, user authorization, dependent jobs, work processes and application logs before rerunning.</p>`},
spool:{title:"SAP Spool Administration",cat:"BASIS",html:`<div class="eyebrow">SPOOL</div><h2>SAP Spool Administration</h2><p>Spool management controls SAP output requests and their delivery to printers or other output destinations.</p><h3>Key transactions</h3><p>SP01 is used to monitor spool requests and SPAD is used for output devices and printer administration.</p>`},
rfc:{title:"SAP RFC & SM59",cat:"BASIS",html:`<div class="eyebrow">CONNECTIVITY</div><h2>SAP RFC & SM59</h2><p>Remote Function Calls allow SAP systems and external components to communicate through configured destinations.</p><h3>SM59 checks</h3><ul><li>Destination type and target host.</li><li>Connection test and authorization test.</li><li>Gateway/network reachability.</li><li>Technical user and password/certificate validity.</li></ul>`},
kernel:{title:"SAP Kernel Upgrade",cat:"BASIS",html:`<div class="eyebrow">LIFECYCLE</div><h2>SAP Kernel Upgrade</h2><p>The kernel contains core SAP executable components. Upgrades are performed to meet compatibility, security and support requirements.</p><h3>High-level flow</h3><p>Check PAM/support requirements → download compatible kernel → plan downtime → back up/verify → stop SAP → replace kernel files using the approved procedure → start SAP → validate processes, versions and application connectivity.</p>`},
sum:{title:"SUM, SPAM & SAINT",cat:"S/4HANA",html:`<div class="eyebrow">SAP LIFECYCLE</div><h2>SUM, SPAM & SAINT</h2><p>These tools serve different lifecycle purposes. SUM handles larger upgrade/update procedures; SPAM manages support packages; SAINT is used for add-on installation and upgrade activities.</p><h3>Interview point</h3><p>Always identify the target software component, SAP release, maintenance requirement and supported tool before choosing the procedure.</p>`},
refresh:{title:"System Refresh vs Client Copy",cat:"BASIS",html:`<div class="eyebrow">SYSTEM ADMINISTRATION</div><h2>System Refresh vs Client Copy</h2><p>A system refresh replaces or synchronizes a target system's data/configuration from a source system according to the chosen refresh procedure. A client copy moves client-specific data inside or between SAP systems using supported client-copy methods.</p><h3>Simple distinction</h3><p>System refresh is a broader system-level activity; client copy is focused on a client and its data.</p>`},
ha:{title:"SAP High Availability & HANA Replication",cat:"Troubleshooting",html:`<div class="eyebrow">HIGH AVAILABILITY</div><h2>High Availability & HANA System Replication</h2><p>HA design aims to reduce service interruption when infrastructure or software components fail.</p><h3>Common concepts</h3><p>ASCS/ERS for central services protection, clustering/failover at the infrastructure layer, and HANA System Replication for database availability. Always validate the actual HA design and runbook before a failover.</p>`},
solman:{title:"SAP Solution Manager & Managed Systems",cat:"BASIS",html:`<div class="eyebrow">SAP OPERATIONS</div><h2>Solution Manager & Managed Systems</h2><p>SAP Solution Manager can provide monitoring, service management, diagnostics and lifecycle capabilities for managed SAP systems.</p><h3>Typical BASIS work</h3><p>Establish trusted connections, configure managed-system data, agents and monitoring, then validate technical system information and alerts.</p>`},
backup:{title:"SAP HANA Backup & Recovery",cat:"HANA",html:`<div class="eyebrow">DATABASE</div><h2>SAP HANA Backup & Recovery</h2><p>A backup strategy should protect data against logical errors, infrastructure failures and disaster scenarios.</p><h3>BASIS checklist</h3><p>Define full/data backups, log backups, retention, destination capacity, encryption where required, monitoring and periodic restore testing. A backup is only useful if recovery is tested.</p>`},
ssl:{title:"SAP SSL Certificates & STRUST",cat:"Cloud",html:`<div class="eyebrow">CERTIFICATES</div><h2>SAP SSL Certificates & STRUST</h2><p>STRUST is used to manage SAP PSEs and trust certificates for secure communication.</p><h3>Renewal mindset</h3><p>Check certificate expiry, obtain the correct signed certificate chain, update the appropriate PSE, validate the trust chain and test the affected HTTPS/RFC/integration connection.</p>`},
aws:{title:"SAP on AWS: BASIS Perspective",cat:"Cloud",html:`<div class="eyebrow">CLOUD OPERATIONS</div><h2>SAP on AWS: BASIS Perspective</h2><p>Running SAP on AWS combines SAP administration with cloud infrastructure concepts such as EC2, storage, networking, security groups, load balancing, DNS, backup and monitoring.</p><h3>BASIS focus</h3><p>Understand where the SAP layer ends and the cloud infrastructure layer begins, then work with the AWS team using clear evidence and ownership boundaries.</p>`},
};

const scenarioGuides={
systemdown:{title:"SAP System Down — Incident Playbook",cat:"P1 / Availability",html:`<h2>SAP System Down — Incident Playbook</h2><p><b>Goal:</b> restore service safely while preserving evidence for RCA.</p><h3>1. Confirm the symptom</h3><p>Check whether the issue affects all users, one application server, one interface, or the entire system. Confirm the exact start time.</p><h3>2. Check the infrastructure layer</h3><ul><li>Server/VM reachable?</li><li>CPU, memory and filesystem healthy?</li><li>Required mounts available?</li><li>Database host reachable?</li></ul><h3>3. Check SAP processes</h3><p>Use <code>sapcontrol -nr &lt;NN&gt; -function GetProcessList</code>. Identify whether ASCS, PAS, AAS or other services are stopped/grey.</p><h3>4. Read evidence</h3><p>Review SAP work-process traces, message server traces, system logs and database alerts around the incident timestamp.</p><h3>5. Recovery</h3><p>Follow the approved restart/failover runbook. Validate logon, transactions, RFCs, jobs and interfaces after recovery.</p><h3>RCA evidence</h3><p>Capture timeline, failed component, error text, actions taken, recovery time and preventive action.</p>`},
slow:{title:"SAP Slow — Performance Playbook",cat:"P1 / Performance",html:`<h2>SAP Slow — Performance Playbook</h2><h3>Start with four questions</h3><ol><li>Who is affected?</li><li>Which transaction/process?</li><li>When did it start?</li><li>Is it consistently slow or intermittent?</li></ol><h3>Evidence path</h3><p><b>ST03N</b> → identify workload and response-time pattern → <b>STAD</b> → drill into individual records → <b>SM50/SM66</b> → inspect work processes → DB/infrastructure monitoring → correlate changes.</p><h3>Do not guess</h3><p>A high response time does not automatically mean the database is the problem. Compare DB time, CPU time and wait components and use evidence to isolate the layer.</p>`},
transport:{title:"Transport RC 8 / RC 12 — Troubleshooting",cat:"HIGH / Transport",html:`<h2>Transport RC 8 / RC 12 — Troubleshooting</h2><h3>First action</h3><p>Open the import log in STMS and find the first meaningful error. Later errors may be consequences.</p><h3>Check</h3><ul><li>Object and program/class/table mentioned in the log.</li><li>Transport sequence and dependencies.</li><li>Target system availability and filesystem space.</li><li>DDIC/object activation or syntax issues.</li><li>Whether a previous transport changed the same object.</li></ul><h3>Recovery</h3><p>Coordinate with the development/application owner, correct the root cause, create the appropriate follow-up transport if needed, then re-import through the normal change process.</p>`},
hanaDisk:{title:"HANA Disk Usage Critical — Troubleshooting",cat:"HIGH / Database",html:`<h2>HANA Disk Usage Critical — Troubleshooting</h2><h3>Separate the problem</h3><p>Determine whether the growth is in data/persistence, log area, backup destination or an operating-system filesystem.</p><h3>Check</h3><ul><li>Filesystem capacity and growth rate.</li><li>HANA alerts and database usage.</li><li>Recent backup/log-backup behavior.</li><li>Long-running transactions or unusual workload.</li></ul><h3>Important</h3><p>Never manually delete database files to create space. Use the approved HANA/storage procedure and coordinate with the DB/storage team for capacity or cleanup actions.</p>`},
job:{title:"Cancelled Background Job — Troubleshooting",cat:"MEDIUM / Jobs",html:`<h2>Cancelled Background Job — Troubleshooting</h2><h3>SM37 checklist</h3><ol><li>Open job log.</li><li>Identify the failed step and program.</li><li>Check the executing user.</li><li>Check ST22 for an ABAP dump.</li><li>Check application logs and variants.</li><li>Check system/work-process resources if the job terminated due to resource constraints.</li></ol><p>Only rerun after confirming whether the failure was transient or caused by data, configuration or authorization.</p>`},
rfc:{title:"RFC Failure — Troubleshooting",cat:"MEDIUM / Connectivity",html:`<h2>RFC Failure — Troubleshooting</h2><h3>SM59 sequence</h3><ol><li>Run Connection Test.</li><li>Run Authorization Test where applicable.</li><li>Check destination host/service and network reachability.</li><li>Check technical user, password or certificate.</li><li>Check gateway and relevant traces if required.</li></ol><p>Classify the failure as network, authentication/authorization, SAP destination configuration or target application failure.</p>`},
ssl:{title:"Expired SSL Certificate — Troubleshooting",cat:"MEDIUM / Security",html:`<h2>Expired SSL Certificate — Troubleshooting</h2><ol><li>Confirm the expiry date and affected endpoint.</li><li>Identify the correct PSE in STRUST.</li><li>Obtain the approved certificate and full trust chain.</li><li>Update the PSE following the change procedure.</li><li>Validate the certificate chain and retest the integration.</li></ol><p>Record the new expiry date and establish monitoring/reminders so the issue does not recur.</p>`},
user:{title:"SAP User Login Failure — Troubleshooting",cat:"MEDIUM / Users",html:`<h2>SAP User Login Failure — Troubleshooting</h2><h3>Separate the symptom</h3><p>Is the user locked, password expired, unauthorized for the transaction, unable to authenticate through SSO, or unable to reach the system?</p><h3>Checks</h3><p>Use SU01 for user status, review the exact error message, and for SSO/Fiori scenarios validate the trust/authentication path. Avoid assigning broad roles as a quick fix.</p>`}
};

const grid=document.getElementById("articleGrid"), search=document.getElementById("articleSearch"), filter=document.getElementById("categoryFilter"), noResults=document.getElementById("noResults");
function applyFilters(){const q=search.value.toLowerCase(), f=filter.value;let shown=0;document.querySelectorAll(".article-card").forEach(c=>{const ok=(f==="all"||c.dataset.category===f)&&(c.dataset.title.toLowerCase().includes(q)||c.innerText.toLowerCase().includes(q));c.style.display=ok?"flex":"none";if(ok)shown++});noResults.style.display=shown?"none":"block"}
search.addEventListener("input",applyFilters);filter.addEventListener("change",applyFilters);

const modal=document.getElementById("modal"), content=document.getElementById("modalContent");
document.querySelectorAll(".read-btn").forEach(b=>b.addEventListener("click",()=>{content.innerHTML=articles[b.dataset.article].html;modal.classList.add("open");document.body.style.overflow="hidden"}));
document.getElementById("closeModal").onclick=()=>{modal.classList.remove("open");document.body.style.overflow=""};
modal.addEventListener("click",e=>{if(e.target===modal){modal.classList.remove("open");document.body.style.overflow=""}});

const overlay=document.getElementById("searchOverlay"), gs=document.getElementById("globalSearch"), results=document.getElementById("searchResults");
document.getElementById("searchBtn").onclick=()=>{overlay.classList.add("open");gs.focus()};
document.getElementById("closeSearch").onclick=()=>overlay.classList.remove("open");
gs.addEventListener("input",()=>{const q=gs.value.toLowerCase().trim();results.innerHTML="";if(!q)return;Object.entries(articles).filter(([k,a])=>(a.title+" "+a.cat).toLowerCase().includes(q)).forEach(([k,a])=>{const d=document.createElement("div");d.className="result";d.innerHTML=`<b>${a.title}</b><small>${a.cat} · Read article</small>`;d.onclick=()=>{overlay.classList.remove("open");content.innerHTML=a.html;modal.classList.add("open");document.body.style.overflow="hidden"};results.appendChild(d)})});

document.getElementById("themeBtn").onclick=()=>document.body.classList.toggle("light");
document.getElementById("menuBtn").onclick=()=>{const n=document.getElementById("nav");n.style.display=n.style.display==="flex"?"none":"flex";n.style.position="absolute";n.style.top="72px";n.style.left="0";n.style.right="0";n.style.padding="20px";n.style.background="#07111f";n.style.flexDirection="column"};

document.querySelectorAll(".scenario-btn").forEach(b=>b.addEventListener("click",()=>{
  const s=scenarioGuides[b.dataset.scenario];
  content.innerHTML=`<div class="eyebrow">${s.cat}</div>${s.html}`;
  modal.classList.add("open");
  document.body.style.overflow="hidden";
}));

window.addEventListener("scroll",()=>{const h=document.documentElement.scrollHeight-innerHeight;document.getElementById("progress").style.width=(scrollY/h*100)+"%"});
